name: CI
on:
  push:
    branches:
      - master
      - new-workflow
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        env TEST_LANG="c" nimble test
        # run test against intx
        env TEST_LANG="cpp" nimble test
        # test conditional compilation for arm64 arch
        # without running the binary
        nim c -c --cpu:arm64 --os:linux tests/all_tests
